[package]
name = "propwriter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
windows = "0.13.0"

[build-dependencies]
windows = "0.13.0"

